// Thicket interop scenario 3: IDENTITY REFERENCE VECTORS.
//
// Copyright (C) 2026 Thicket contributors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// The gap this closes
// -------------------
// Every interop scenario uses Identity and none of them asserts it. A scenario
// can pass end to end while key derivation is subtly wrong, provided both ends
// are wrong the same way -- and that is precisely the failure mode of a C++
// port whose crypto has only ever been checked against itself.
//
// This binary asserts microReticulum's Identity against fixed outputs produced
// by the Python reference (src/vectors.h, generated by
// python/identity_vectors.py --emit). No network, no second process: it is a
// pure comparison against the reference's arithmetic.
//
// The scenario's Python half re-derives the same vectors under the current RNS
// and diffs them, so the constants cannot silently rot when the pin moves.
//
// Exit 0 iff every vector matches.

#include <microStore/FileSystem.h>
#include <microStore/Adapters/UniversalFileSystem.h>

#include <microReticulum.h>

#include <microReticulum/Cryptography/HKDF.h>

#include "vectors.h"

#include <stdio.h>
#include <string>

static int checks = 0;
static int failures = 0;
static int divergences = 0;

static RNS::Bytes from_hex(const char* hex) {
	RNS::Bytes b;
	b.appendHex(hex);
	return b;
}

static void check_hex(const char* what, const RNS::Bytes& got, const char* want) {
	++checks;
	const std::string got_hex = got.toHex();
	if (got_hex == want) {
		printf("[cpp]   OK   %-16s %s\n", what, got_hex.c_str());
	}
	else {
		++failures;
		printf("[cpp]   FAIL %-16s\n", what);
		printf("[cpp]          got:  %s\n", got_hex.c_str());
		printf("[cpp]          want: %s\n", want);
	}
}

static void check_bool(const char* what, bool got, bool want) {
	++checks;
	if (got == want) {
		printf("[cpp]   OK   %-16s %s\n", what, got ? "true" : "false");
	}
	else {
		++failures;
		printf("[cpp]   FAIL %-16s got %s, want %s\n", what,
		       got ? "true" : "false", want ? "true" : "false");
	}
}

int main() {
	printf("[cpp] identity_vectors starting (vectors generated against RNS %s)\n",
	       VEC_RNS_VERSION);

	// Identity touches the filesystem via the known-destinations store even
	// when we never persist anything, so give it one.
	microStore::FileSystem filesystem{microStore::Adapters::UniversalFileSystem()};
	filesystem.init();
	RNS::Utilities::OS::register_filesystem(filesystem);

	const RNS::Bytes private_key = from_hex(VEC_PRIVATE_KEY);
	const RNS::Bytes message     = from_hex(VEC_MESSAGE);
	const RNS::Bytes plaintext   = from_hex(VEC_PLAINTEXT);
	const RNS::Bytes ciphertext  = from_hex(VEC_CIPHERTEXT);
	const RNS::Bytes signature   = from_hex(VEC_SIGNATURE);

	// --- hashing -----------------------------------------------------------
	check_hex("full_hash",      RNS::Identity::full_hash(message),      VEC_FULL_HASH);
	check_hex("truncated_hash", RNS::Identity::truncated_hash(message), VEC_TRUNCATED_HASH);

	// --- HKDF --------------------------------------------------------------
	// The key-derivation function under every encrypted packet. Asserted
	// directly rather than inferred from a scenario passing.
	//
	// This is the shape every real caller uses: a non-empty salt (the identity
	// hash) and an empty context (Identity::get_context() returns nothing, and
	// so does the reference's).
	check_hex("hkdf",
	          RNS::Cryptography::hkdf(VEC_HKDF_LENGTH,
	                                  from_hex(VEC_HKDF_SECRET),
	                                  from_hex(VEC_HKDF_SALT),
	                                  {RNS::Bytes::NONE}),
	          VEC_HKDF_OUTPUT_NOCTX);

	// The reference substitutes 32 zero bytes when no salt is given. Nothing
	// in either stack takes this path today; checked so that "nothing takes
	// this path" stays a fact rather than an assumption.
	check_hex("hkdf(no salt)",
	          RNS::Cryptography::hkdf(VEC_HKDF_LENGTH,
	                                  from_hex(VEC_HKDF_SECRET),
	                                  {RNS::Bytes::NONE},
	                                  {RNS::Bytes::NONE}),
	          VEC_HKDF_OUTPUT_NOSALT);

	// --- KNOWN DIVERGENCE ---------------------------------------------------
	// RNS::Cryptography::hkdf() takes a `context` argument and never uses it.
	// Cryptography/HKDF.cpp calls HKDFCommon::extract(out, len) and drops the
	// context on the floor, even though the underlying attermann/Crypto API
	// (HKDF.h:36) accepts `extract(out, outLen, info, infoLen)`. The reference
	// mixes context into every expansion block.
	//
	// Impact today is nil: get_context() returns empty on both sides, so no
	// packet is affected. It is still a silently-wrong public function, and the
	// next caller to pass a context gets keys the reference will not agree with.
	//
	// Pinned as an EXPECTED divergence rather than ignored. The exemption is
	// strict: if the behaviour is ever corrected, this check FAILS and forces
	// the exemption to be deleted, so the suite cannot quietly keep excusing a
	// bug that no longer exists.
	{
		const RNS::Bytes with_context =
		    RNS::Cryptography::hkdf(VEC_HKDF_LENGTH,
		                            from_hex(VEC_HKDF_SECRET),
		                            from_hex(VEC_HKDF_SALT),
		                            from_hex(VEC_HKDF_CONTEXT));
		++checks;
		const std::string got = with_context.toHex();
		if (got == VEC_HKDF_OUTPUT) {
			++failures;
			printf("[cpp]   FAIL %-16s hkdf now honours `context` and matches the\n",
			       "hkdf(context)");
			printf("[cpp]          reference. The known-divergence exemption in\n");
			printf("[cpp]          identity_vectors/src/main.cpp is stale -- delete it\n");
			printf("[cpp]          and make this a normal check_hex().\n");
		}
		else if (got == std::string(VEC_HKDF_OUTPUT_NOCTX)) {
			++divergences;
			printf("[cpp]   XFAIL %-15s ignores `context` (known divergence, see source)\n",
			       "hkdf(context)");
		}
		else {
			++failures;
			printf("[cpp]   FAIL %-16s diverges from the reference in a NEW way\n",
			       "hkdf(context)");
			printf("[cpp]          got:            %s\n", got.c_str());
			printf("[cpp]          reference:      %s\n", VEC_HKDF_OUTPUT);
			printf("[cpp]          known-bad was:  %s\n", VEC_HKDF_OUTPUT_NOCTX);
		}
	}

	// --- key derivation ----------------------------------------------------
	RNS::Identity identity(false);
	if (!identity.load_private_key(private_key)) {
		printf("[cpp] FAIL: load_private_key rejected the reference key\n");
		return 1;
	}

	// This one is load-bearing beyond what it looks like. X25519 requires the
	// scalar to be clamped per RFC 7748; the reference clamps on ingestion in
	// from_private_bytes(). An implementation that clamps only for generated
	// keys produces a DIFFERENT public key for the same imported bytes, and
	// every scenario still passes because both ends of a C++-only test agree.
	check_hex("public_key",    identity.get_public_key(), VEC_PUBLIC_KEY);
	check_hex("identity_hash", identity.hash(),           VEC_IDENTITY_HASH);
	check_hex("dest_hash",
	          RNS::Destination::hash(identity, VEC_APP_NAME, VEC_ASPECTS),
	          VEC_DEST_HASH);

	// --- signing -----------------------------------------------------------
	// Ed25519 is deterministic (RFC 8032), so the C++ signature over the same
	// message with the same key must be byte-identical to the reference's.
	check_hex("sign", identity.sign(message), VEC_SIGNATURE);

	check_bool("validate", identity.validate(signature, message), true);

	// A validator that accepts everything would pass the line above, so check
	// that a one-bit change is rejected.
	RNS::Bytes bad_signature(signature.left(signature.size() - 1));
	bad_signature.append((uint8_t)(signature.data()[signature.size() - 1] ^ 0x01));
	check_bool("validate(bad)", identity.validate(bad_signature, message), false);

	// A signature over a different message must also be rejected.
	RNS::Bytes other_message(message);
	other_message.append("!");
	check_bool("validate(other)", identity.validate(signature, other_message), false);

	// --- decryption --------------------------------------------------------
	// The reference produced this ciphertext with an ephemeral X25519 key.
	// Recovering the plaintext exercises ECDH, HKDF, AES-CBC, PKCS#7 and the
	// HMAC check together, against bytes we did not produce.
	const RNS::Bytes recovered = identity.decrypt(ciphertext);
	check_hex("decrypt", recovered, VEC_PLAINTEXT);

	// --- round trip --------------------------------------------------------
	// Our own ciphertext must at least decrypt back, which catches an encrypt
	// path that is broken in a way the decrypt path happens to mirror only for
	// reference input.
	const RNS::Bytes ours = identity.encrypt(plaintext);
	check_hex("encrypt/decrypt", identity.decrypt(ours), VEC_PLAINTEXT);

	int rc = 0;
	if (failures > 0) {
		printf("[cpp] FAIL: %d of %d identity vectors failed\n", failures, checks);
		rc = 1;
	}
	else {
		// Say exactly what passed. A divergence is not a match, and a summary
		// that rounds it up to one is how a known bug stops being known.
		printf("[cpp] SUCCESS %d of %d identity vectors matched the Python "
		       "reference; %d known divergence(s) still present\n",
		       checks - divergences, checks, divergences);
	}
	printf("[cpp] exit code %d\n", rc);
	return rc;
}
