#!/usr/bin/env python3
# Copyright (C) 2026 Thicket contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Three Tamzen bold faces as the WEIGHT Cozette lacks.
#
# Cozette stays the body face and the fallback face. Tamzen supplies only bold:
# an inline `! run at 6x12, an H3 at 7x13, an H2 at 8x16. Every face is ASCII
# plus Latin-1; anything outside that falls back to Cozette, which is why the
# body row keeps Cozette's pitch and every advance here is a monospace cell.
#
#   python3 scripts/bdf2tamzen.py lib/SharpLcd/src/TamzenFont.h \
#       BOLD6 /tmp/Tamzen6x12b.bdf  BOLD7 /tmp/Tamzen7x13b.bdf  BOLD8 /tmp/Tamzen8x16b.bdf

import sys
from collections import Counter

FIRST, LAST = 32, 126
EXTRA = list(range(0x00A0, 0x0100))          # accented Latin, so bold prose works


def parse(path):
    asc = desc = None; glyphs = {}
    enc = bbx = dw = None; bits = None
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.rstrip("\n")
        if   line.startswith("FONT_ASCENT"):  asc = int(line.split()[1])
        elif line.startswith("FONT_DESCENT"): desc = int(line.split()[1])
        elif line.startswith("ENCODING"):     enc = int(line.split()[1])
        elif line.startswith("DWIDTH") and enc is not None: dw = int(line.split()[1])
        elif line.startswith("BBX"):          bbx = [int(v) for v in line.split()[1:]]
        elif line == "BITMAP":                bits = []
        elif line == "ENDCHAR":
            if bits is not None and enc is not None and (FIRST <= enc <= LAST or enc in EXTRA):
                glyphs[enc] = (bbx, bits, dw)
            enc = bbx = bits = dw = None
        elif bits is not None and line and all(c in "0123456789abcdefABCDEF" for c in line):
            bits.append(line)
    return asc, desc, glyphs


def render(bbx, rows, cell_w, cell_h, ascent):
    gw, gh, xoff, yoff = bbx
    out = [0] * cell_h                         # one byte per row, bit 7 leftmost
    for i, hexrow in enumerate(rows):
        val = int(hexrow, 16); nbits = len(hexrow) * 4
        y = ascent - yoff - gh + i
        if not (0 <= y < cell_h): continue
        acc = 0
        for x in range(min(nbits, gw)):
            if (val >> (nbits - 1 - x)) & 1:
                px = x + xoff
                if 0 <= px < cell_w: acc |= 0x80 >> px
        out[y] |= acc
    return out


def face(name, path):
    asc, desc, glyphs = parse(path)
    cell_h = asc + desc
    adv = Counter(g[2] for g in glyphs.values()).most_common(1)[0][0]
    ink = max(g[0][0] + max(0, g[0][2]) for g in glyphs.values())
    if ink > 8: sys.exit(f"{path}: ink {ink} needs more than one byte a row")
    keep = [c for c in list(range(FIRST, LAST + 1)) + EXTRA if c in glyphs]
    lines = [
        f"// {name}: advance {adv}, ink {ink}x{cell_h}, ascent {asc}. {len(keep)} glyphs.",
        f"static const uint8_t  {name}_W = {adv};",
        f"static const uint8_t  {name}_H = {cell_h};",
        f"static const uint8_t  {name}_ASCENT = {asc};",
        "struct " + name + "Glyph { uint16_t cp; uint8_t rows[%d]; };" % cell_h,
        f"static const uint16_t {name}_COUNT = {len(keep)};",
        f"static const {name}Glyph {name}[{len(keep)}] = {{",
    ]
    for c in keep:
        r = render(*glyphs[c][:2], ink, cell_h, asc)
        lines.append("\t{0x%04X, {%s}}," % (c, ",".join(f"0x{v:02X}" for v in r)))
    lines += ["};", ""]
    return "\n".join(lines), len(keep) * (2 + cell_h)


def main():
    dst = sys.argv[1]
    pairs = sys.argv[2:]
    out = [
        "// Generated by scripts/bdf2tamzen.py -- do not edit.",
        "// Source: Tamzen by Suraj N. Kurapati, from the Tamsyn font (MIT-like).",
        "// Bold weight only: Cozette is body and fallback, Tamzen is emphasis.",
        "", "#pragma once", "", "#include <stdint.h>", "", "namespace thicket {", "",
    ]
    total = 0
    for i in range(0, len(pairs), 2):
        block, size = face(pairs[i], pairs[i + 1])
        out.append(block); total += size
    out += ["}  // namespace thicket", ""]
    open(dst, "w").write("\n".join(out))
    print(f"[bdf2tamzen] {dst}: three faces, {total} bytes of tables")


if __name__ == "__main__":
    main()
