#!/usr/bin/env python3
# Copyright (C) 2026 Thicket contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Convert a BDF bitmap font to a C header for the display driver.
# ASCII 32..126 only; one byte per row, bit 7 leftmost.
#
#   python3 scripts/bdf2header.py cozette.bdf lib/SharpLcd/src/CozetteFont.h

import re
import sys

FIRST, LAST = 32, 126


def parse(path):
    ascent = descent = None
    glyphs = {}
    enc = bbx = dwidth = None
    bits = None
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.rstrip("\n")
        if line.startswith("FONT_ASCENT"):
            ascent = int(line.split()[1])
        elif line.startswith("FONT_DESCENT"):
            descent = int(line.split()[1])
        elif line.startswith("ENCODING"):
            enc = int(line.split()[1])
        elif line.startswith("DWIDTH") and enc is not None:
            dwidth = int(line.split()[1])
        elif line.startswith("BBX"):
            bbx = [int(v) for v in line.split()[1:]]
        elif line == "BITMAP":
            bits = []
        elif line == "ENDCHAR":
            if bits is not None and enc is not None and FIRST <= enc <= LAST:
                glyphs[enc] = (bbx, bits, dwidth)
            enc = bbx = bits = dwidth = None
        elif bits is not None and re.fullmatch(r"[0-9A-Fa-f]+", line):
            bits.append(line)
    # Width comes from the glyphs actually kept. Taking it across the whole
    # font picks up 13px CJK and box-drawing cells that are never emitted.
    cell_w = max(g[2] for g in glyphs.values())
    return ascent, descent, cell_w, glyphs


def render(bbx, rows, dwidth, cell_w, cell_h, ascent):
    """Place a glyph's bitmap into a fixed cell, top-left origin."""
    gw, gh, xoff, yoff = bbx
    out = [0] * cell_h
    for i, hexrow in enumerate(rows):
        # BDF pads each row to whole bytes, MSB leftmost.
        val = int(hexrow, 16)
        nbits = len(hexrow) * 4
        row = [(val >> (nbits - 1 - b)) & 1 for b in range(min(nbits, gw))]
        y = ascent - yoff - gh + i          # baseline-relative to top-left
        if not (0 <= y < cell_h):
            continue
        acc = 0
        for x, on in enumerate(row):
            px = x + xoff
            if on and 0 <= px < cell_w:
                acc |= 0x80 >> px
        out[y] |= acc
    return out


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: bdf2header.py IN.bdf OUT.h")
    src, dst = sys.argv[1], sys.argv[2]
    ascent, descent, cell_w, glyphs = parse(src)
    cell_h = ascent + descent

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit(f"{src}: missing glyphs for {missing}")
    if cell_w > 8:
        sys.exit(f"{src}: {cell_w}px wide does not fit one byte per row")

    lines = [
        "// Generated by scripts/bdf2header.py -- do not edit.",
        f"// Source: {src.split('/')[-1]}, Cozette by Ines (MIT).",
        f"// {cell_w}x{cell_h} cell, ascent {ascent}, one byte per row, bit 7 leftmost.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "namespace thicket {",
        "",
        f"static const uint8_t FONT_W = {cell_w};",
        f"static const uint8_t FONT_H = {cell_h};",
        f"static const uint8_t FONT_FIRST = {FIRST};",
        f"static const uint8_t FONT_LAST = {LAST};",
        "",
        f"static const uint8_t FONT[{LAST - FIRST + 1}][{cell_h}] = {{",
    ]
    for c in range(FIRST, LAST + 1):
        rows = render(*glyphs[c], cell_w, cell_h, ascent)
        body = ",".join(f"0x{v:02X}" for v in rows)
        ch = chr(c).replace("\\", "backslash")
        lines.append(f"\t{{{body}}},  // {c} {ch!r}" if c != 39 else
                     f"\t{{{body}}},  // {c} apostrophe")
    lines += ["};", "", "}  // namespace thicket", ""]

    open(dst, "w").write("\n".join(lines))
    print(f"[bdf2header] {cell_w}x{cell_h}, {LAST-FIRST+1} glyphs -> {dst}")


if __name__ == "__main__":
    main()
