#!/usr/bin/env python3
# Copyright (C) 2026 Thicket contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Cozette hi-DPI (12x26) as a second, HEADING-ONLY face.
#
# ASCII plus Latin-1 Supplement only. A heading is a line of a page title, not a
# box-drawing canvas, and every glyph here costs 52 bytes against the 6x13
# face's 13. Anything outside the range falls back to the small face, which is
# what the renderer does rather than drawing a hole at double size.
#
#   python3 scripts/bdf2big.py cozette_hidpi.bdf lib/SharpLcd/src/CozetteBig.h

import sys
from collections import Counter

FIRST, LAST = 32, 126
EXTRA = list(range(0x00A0, 0x0100))          # accented headings


def parse(path):
    asc = desc = None; glyphs = {}
    enc = bbx = dw = None; bits = None
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.rstrip("\n")
        if line.startswith("FONT_ASCENT"):    asc = int(line.split()[1])
        elif line.startswith("FONT_DESCENT"): desc = int(line.split()[1])
        elif line.startswith("ENCODING"):     enc = int(line.split()[1])
        elif line.startswith("DWIDTH") and enc is not None: dw = int(line.split()[1])
        elif line.startswith("BBX"):          bbx = [int(v) for v in line.split()[1:]]
        elif line == "BITMAP":                bits = []
        elif line == "ENDCHAR":
            if bits is not None and enc is not None and (FIRST <= enc <= LAST or enc in EXTRA):
                glyphs[enc] = (bbx, bits, dw)
            enc = bbx = bits = dw = None
        elif bits is not None and all(c in "0123456789abcdefABCDEF" for c in line) and line:
            bits.append(line)
    return asc, desc, glyphs


def render(bbx, rows, cell_w, cell_h, ascent):
    gw, gh, xoff, yoff = bbx
    out = [0] * cell_h                       # 16-bit rows, bit 15 leftmost
    for i, hexrow in enumerate(rows):
        val = int(hexrow, 16); nbits = len(hexrow) * 4
        y = ascent - yoff - gh + i
        if not (0 <= y < cell_h): continue
        acc = 0
        for x in range(min(nbits, gw)):
            if (val >> (nbits - 1 - x)) & 1:
                px = x + xoff
                if 0 <= px < cell_w: acc |= 0x8000 >> px
        out[y] |= acc
    return out


def main():
    if len(sys.argv) != 3: sys.exit("usage: bdf2big.py IN.bdf OUT.h")
    src, dst = sys.argv[1], sys.argv[2]
    asc, desc, glyphs = parse(src)
    cell_h = asc + desc
    advance = Counter(g[2] for g in glyphs.values()).most_common(1)[0][0]
    # Drop anything not one cell wide, same rule as the small face.
    over = sorted(c for c, g in glyphs.items() if g[2] != advance)
    for c in over: del glyphs[c]
    cell_w = max(g[0][0] + max(0, g[0][2]) for g in glyphs.values())
    if cell_w > 16: sys.exit(f"{src}: ink {cell_w} needs more than two bytes a row")

    keep = [c for c in list(range(FIRST, LAST + 1)) + EXTRA if c in glyphs]
    L = [
        "// Generated by scripts/bdf2big.py -- do not edit.",
        f"// Source: {src.split('/')[-1]}, Cozette hi-DPI by Ines (MIT).",
        f"// advance {advance}, ink {cell_w}x{cell_h}, ascent {asc}, bit 15 leftmost.",
        "//",
        "// HEADINGS ONLY. 52 bytes a glyph against the 6x13 face's 13, so this",
        "// carries ASCII and Latin-1 and nothing else; the renderer falls back to",
        "// the small face for anything outside that.",
        "", "#pragma once", "", "#include <stdint.h>", "", "namespace thicket {", "",
        f"static const uint8_t  BIGFONT_W = {advance};",
        f"static const uint8_t  BIGFONT_INK_W = {cell_w};",
        f"static const uint8_t  BIGFONT_H = {cell_h};",
        "",
        "struct BigGlyph { uint16_t cp; uint16_t rows[%d]; };" % cell_h,
        f"static const uint16_t BIGFONT_COUNT = {len(keep)};",
        f"static const BigGlyph BIGFONT[{len(keep)}] = {{",
    ]
    for c in keep:
        rows = render(*glyphs[c][:2], cell_w, cell_h, asc)
        L.append("\t{0x%04X, {%s}}," % (c, ",".join(f"0x{v:04X}" for v in rows)))
    L += ["};", "", "}  // namespace thicket", ""]
    open(dst, "w").write("\n".join(L))
    print(f"[bdf2big] {cell_w}x{cell_h}, advance {advance}, {len(keep)} glyphs -> {dst}")
    print(f"[bdf2big] table {len(keep) * (2 + 2 * cell_h)} bytes")


if __name__ == "__main__":
    main()
